---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-rbac-engine-chart.fullname" . }}-extension-apiserver-authentication-reader
  namespace: kube-system
  labels:
    {{- include "k8s-rbac-engine-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-rbac-engine-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
