---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-rbac-engine-chart.fullname" . }}
  labels:
    {{- include "k8s-rbac-engine-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: apiserver
      protocol: TCP
      name: apiserver
  selector:
    {{- include "k8s-rbac-engine-chart.selectorLabels" . | nindent 4 }}
